export { default as Carousel } from './Carousel.vue'
export { default as CarouselItem } from './CarouselItem.vue'
export { type CarouselProps } from './interface'
// export type { UnwrapRefCarouselApi as CarouselApi } from './interface'
// export { useCarousel } from './useCarousel'
